export const MobileStatesEnum = {
    NOT_JOINED_STATE: 'NOT_JOINED_STATE',
    WAITING_FOR_START_STATE: 'WAITING_FOR_START_STATE',
    MAFIA_INFO_STATE: 'MAFIA_INFO_STATE',
    CITIZEN_INFO_STATE: 'CITIZEN_INFO_STATE',
    AGENT_INFO_STATE: 'AGENT_INFO_STATE',
    SLEEP_STATE: 'SLEEP_STATE',
    AGENT_CHECKS_STATE: 'AGENT_CHECKS_STATE',
    AGENT_CHECKED_STATE: 'AGENT_CHECKED_STATE',
    AGENT_PROTECTS_STATE: 'AGENT_PROTECTS_STATE',
    AGENT_PROTECTED_STATE: 'AGENT_PROTECTED_STATE',
    MAFIA_KILLS_STATE: 'MAFIA_KILLS_STATE',
    MAFIA_WAITING_STATE: 'MAFIA_WAITING_STATE',
    MAFIA_KILLED_STATE: 'MAFIA_KILLED_STATE',
    ELIMINATED_STATE: 'ELIMINATED_STATE',
    DISCUSSION_STATE: 'DISCUSSION_STATE',
    VOTING_STATE: 'VOTING_STATE',
    VOTING_RESULT_STATE: 'VOTING_RESULT_STATE',
    VOTING_RESULT_DRAW_STATE: 'VOTING_RESULT_DRAW_STATE',
    GAME_OVER_STATE: 'GAME_OVER_STATE',
    STAY_TUNED_STATE: 'STAY_TUNED_STATE',
    FINAL_STATE: 'FINAL_STATE',
    FINAL_BEFORE_GAME_OVER_STATE: 'FINAL_BEFORE_GAME_OVER_STATE',
    DRAW_STATE: 'DRAW_STATE'




};
