export const StatesEnum = {
    AWAITING_PLAYERS_STATE: 'AWAITING_PLAYERS_STATE',
    AWAITING_PLAYERS_READY_STATE: 'AWAITING_PLAYERS_READY_STATE',
    AGENT_CHECKS_STATE: 'AGENT_CHECKS_STATE',
    AGENT_PROTECTS_STATE: 'AGENT_PROTECTS_STATE',
    DISCUSSION_STATE: 'DISCUSSION_STATE',
    DRAW_STATE: 'DRAW_STATE',
    GAME_OVER_STATE: 'GAME_OVER_STATE',
    MAFIA_KILLS_STATE: 'MAFIA_KILLS_STATE',
    VOTING_STATE: 'VOTING_STATE',
    SLEEPING_STATE: 'SLEEPING_STATE'

};
